eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/

server:
    port: 8111

spring:
    main:
        web-application-type: reactive
    application:
        name: spring-cloud-gateway-demo-api
    cloud:
        gateway:
            routes:
                - id: payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
                  uri: lb://spring-cloud-gateway-demo-server        #匹配后提供服务的路由地址
                  predicates:
                      - Path=/test/**         # 断言，路径相匹配的进行路由
                      - Method=GET
                - id: payment_route2
                  uri: lb://spring-cloud-gateway-demo-server
                  predicates:
                      - Path=/payment/lb/**
                  filters:
                      - RewritePath=/test(?<segment>/?.*), $\{segment}